# Spacy Pipeline

- **Goal:** Prediction Recognition

- **Purpose:** To extract named entities (NER), part-of-speech (POS), etc.
    1. Use to train model as feature extraction (ie: TF x IDF) alone isn't enough

- **Misc:**
    - `%store`: Cell magic will store the variable of interest so we can load in another notebook

In [1]:
import os
import sys
import spacy

import pandas as pd
# Get the current working directory of the notebook
notebook_dir = os.getcwd()
# Add the parent directory to the system path
sys.path.append(os.path.join(notebook_dir, '../'))

from pipelines import BasePipeline
from data_processing import DataProcessing

In [2]:
pd.set_option('max_colwidth', 800)
nlp = spacy.load("en_core_web_sm")
%store -r predictions_df
%store -r non_predictions_df

python eval() and df.apply()

In [3]:
predictions_df.head(3)

,Base Sentence,Prediction Label,Model Name,Domain,Template Number
0,"On 2024-10-15, Rachel Patel, a financial analyst, predicts that the operating cash flow at General Motors will likely decrease by $5 billion to $10 billion in Q2 of 2026.",1,llama-3.3-70b-versatile,financial,1
1,"In 2024, Julian Sanchez from Bank of America, forecasts that the stock price will rise from $50 to $75 per share in 2028.",1,llama-3.3-70b-versatile,financial,2
2,"Emily Wilson, a financial expert, predicts on 20/08/2024 that the research and development expenses at Pfizer may stay stable at $15 million in 2029.",1,llama-3.3-70b-versatile,financial,3

In [4]:
base_pipeline = BasePipeline()

cleaned_predictions_df = base_pipeline.clean_predictions(predictions_df)
cleaned_predictions_df

,Base Sentence,Prediction Label,Model Name,Domain,Template Number
0,"on 2024-10-15, rachel patel, a financial analyst, predicts that the operating cash flow at general motors will likely decrease by $5 billion to $10 billion in q2 of 2026.",1,llama-3.3-70b-versatile,financial,1
1,"in 2024, julian sanchez from bank of america, forecasts that the stock price will rise from $50 to $75 per share in 2028.",1,llama-3.3-70b-versatile,financial,2
2,"emily wilson, a financial expert, predicts on 20/08/2024 that the research and development expenses at pfizer may stay stable at $15 million in 2029.",1,llama-3.3-70b-versatile,financial,3
3,"according to a senior executive from cisco, on 2024/08/20, the net profit is expected to increase beyond $8 billion in the timeframe of q4 of 2027.",1,llama-3.3-70b-versatile,financial,4
4,"in 2025-02-18, the revenue at visa has a probability of 20 percent to reach $25 billion, which is a 10% increase, as predicted by david lee, a financial reporter, on 15 oct 2024.",1,llama-3.3-70b-versatile,financial,5
5,"on wednesday, november 20, 2024, michael davis, a financial analyst, predicts that the gross profit at 3m will likely decrease by 15% to $12 billion in q1 of 2026.",1,llama-3.3-70b-versatile,financial,1
6,"in q3 of 2024, olivia brown from johnson & johnson, envisions that the operating income will rise from $10 billion to $15 billion in 2028.",1,llama-3.3-70b-versatile,financial,2
7,"kevin white, a financial expert, predicts on 10/10/2024 that the revenue at at&t may increase by $5 billion to $20 billion in 2027.",1,llama-3.3-70b-versatile,financial,3
8,"according to a top executive from intel, on 2024-07-25, the net profit is expected to increase beyond $12 billion in the timeframe of q2 of 2029.",1,llama-3.3-70b-versatile,financial,4
9,"in 2026-08-25, the stock price at mcdonald's is expected to be $200 per share, which is a 25% increase, as predicted by sophia rodriguez, a financial analyst, on 25 july 2024.",1,llama-3.3-70b-versatile,financial,5
10,"on 2024-10-15, dr. rachel kim, a senior meteorologist at the national oceanic and atmospheric administration, forecasts that the precipitation levels in los angeles will likely increase by 15% in q2 of 2026.",1,llama-3.3-70b-versatile,weather,1
11,"in 2024-08, emily chen from the european centre for medium-range weather forecasts envisions that the humidity in beijing should decrease by 12% in 2027-03.",1,llama-3.3-70b-versatile,weather,2
12,"michael davis, a weather expert from the meteorological office, predicts on 2024-09-20 that the temperature in sydney will fall by 8°c in the timeframe of 2025-09.",1,llama-3.3-70b-versatile,weather,3
13,"according to a top executive from the world meteorological organization, on 2024-11-01, the wind speed in tokyo is expected to rise beyond 20 mph in the timeframe of 2026-06.",1,llama-3.3-70b-versatile,weather,4
14,"in 2028-02, the average sea level in miami has a probability of 10% to increase by 2 inches, as predicted by dr. lisa nguyen, a weather analyst from the national weather service, on 2024-07-15.",1,llama-3.3-70b-versatile,weather,5
15,"on 2024-12-25, james lee, a weather reporter from the korean meteorological administration, forecasts that the snowfall levels in new york city will likely decrease by 5 inches in q1 of 2027.",1,llama-3.3-70b-versatile,weather,1
16,"in 2025-01, david taylor from the australian bureau of meteorology predicts that the air quality index in melbourne will improve by 15% in 2026-10.",1,llama-3.3-70b-versatile,weather,2
17,"dr. sophia patel, a weather expert from the indian meteorological department, predicts on 2024-06-01 that the temperature in mumbai will rise by 5°c in the timeframe of 2027-05.",1,llama-3.3-70b-versatile,weather,3
18,"according to a senior meteorologist from the chinese meteorological administration, on 2024-03-15, the rainfall in shanghai is expected to increase beyond 20% in the timeframe of 2026-08.",1,llama-3.3-70b-versatile,weather,4
19,"in 2029-04, the wind chill in chicago has a probability of 12% to decrease by 8°f, as predicted by dr. kevin white, a weather analyst from the national centers for environmental prediction, on 2024-02-20.",1,llama-3.3-70b-versatile,weather,5
20,"on 2024-10-15, dr. david lee, a health expert, predicts that the average blood pressure at the american heart association will likely decrease by 10% in q2 of 2026.",1,llama-3.3-70b-versatile,health,1
21,"in 2024, dr. maria rodriguez from the world health organization envisions that the global life expectancy may rise from 72 to 75 years in 2028.",1,llama-3.3-70b-versatile,health,2
22,dr. john smith predicts on 08/20/2024 that the prevalence of mental health disorders in the united states should stay stable at 20% in 2027.,1,llama-3.3-70b-versatile,health,3
23,"according to a report by dr. emily chen from the centers for disease control and prevention, on 21 aug 2024, the obesity rate among children is expected to increase beyond 25% in the timeframe of q4 of 2029.",1,llama-3.3-70b-versatile,health,4
24,"in q1 of 2025, the average daily step count in australia is expected to rise by 15%, as predicted by dr. michael brown from the national institutes of health on 2024-10-10.",1,llama-3.3-70b-versatile,health,5
25,"on 2024/11/12, dr. sophia patel, a health analyst, forecasts that the cancer survival rate at the mayo clinic will likely increase by 12% in 2026.",1,llama-3.3-70b-versatile,health,1
26,"in 2025, dr. kevin white from the american cancer society predicts that the average daily caloric intake may fall from 2500 to 2000 calories in quarter 2 of 2028.",1,llama-3.3-70b-versatile,health,2
27,dr. lisa nguyen predicts on 2024-08-25 that the global vaccination rate for influenza in the european union should increase by 15% in 2027.,1,llama-3.3-70b-versatile,health,3
28,"according to a report by dr. daniel kim from the university of california, on 10/15/2024, the prevalence of chronic diseases among adults is expected to decrease beyond 30% in the timeframe of q3 of 2030.",1,llama-3.3-70b-versatile,health,4
29,"in 2029-08-20, the average weekly exercise hours in canada is expected to rise by 20%, as predicted by dr. olivia martin from the canadian medical association on 2024/10/20.",1,llama-3.3-70b-versatile,health,5
30,"on 2024-10-15, policy expert, john smith, predicts that the stock price at goldman sachs will rise by 10% in q2 of 2026.",1,llama-3.3-70b-versatile,policy,1
31,"in 2024, policy analyst, emily johnson, from the federal reserve, envisions that the interest rate will increase from 2% to 4% in 2028.",1,llama-3.3-70b-versatile,policy,2
32,"policy senior level person, michael brown, predicts on 08/20/2024 that the gdp in the united states may stay stable at $20 trillion in 2027.",1,llama-3.3-70b-versatile,policy,3
33,"according to a policy top executive, robert williams, from jpmorgan chase, on 2024-08-22, the number of bank branches is expected to decrease beyond 5,000 in the timeframe of q4 of 2029.",1,llama-3.3-70b-versatile,policy,4
34,"in 2025-08-20, the inflation rate in the european union has a probability of 80% to reach 3%, as predicted by policy reporter, sarah lee, on 2024-10-10.",1,llama-3.3-70b-versatile,policy,5
35,"on 2024/11/12, policy expert, david white, forecasts that the exchange rate at the european central bank will likely decrease by 5% in q1 of 2027.",1,llama-3.3-70b-versatile,policy,1
36,"in q3 of 2024, policy analyst, kevin davis, from the international monetary fund, predicts that the unemployment rate will fall from 5% to 3% in 2026.",1,llama-3.3-70b-versatile,policy,2
37,"policy senior level person, olivia martinez, predicts on 2024-09-18 that the national debt in japan may increase by 10% in 2028.",1,llama-3.3-70b-versatile,policy,3
38,"according to a policy top executive, james wilson, from citigroup, on 2024-10-25, the number of credit card holders is expected to rise beyond 100 million in the timeframe of q2 of 2030.",1,llama-3.3-70b-versatile,policy,4
39,"in q4 of 2027, the number of initial public offerings in the united states is expected to be 500, which is a 20% increase, as predicted by policy analyst, daniel kim, on 2024-08-15.",1,llama-3.3-70b-versatile,policy,5

In [5]:
# predictions_df

In [6]:
only_predictions = DataProcessing.df_to_list(cleaned_predictions_df, 'Base Sentence')
only_predictions

['on 2024-10-15, rachel patel, a financial analyst, predicts that the operating cash flow at general motors will likely decrease by $5 billion to $10 billion in q2 of 2026.',
 'in 2024, julian sanchez from bank of america, forecasts that the stock price will rise from $50 to $75 per share in 2028.',
 'emily wilson, a financial expert, predicts on 20/08/2024 that the research and development expenses at pfizer may stay stable at $15 million in 2029.',
 'according to a senior executive from cisco, on 2024/08/20, the net profit is expected to increase beyond $8 billion in the timeframe of q4 of 2027.',
 'in 2025-02-18, the revenue at visa has a probability of 20 percent to reach $25 billion, which is a 10% increase, as predicted by david lee, a financial reporter, on 15 oct 2024.',
 'on wednesday, november 20, 2024, michael davis, a financial analyst, predicts that the gross profit at 3m will likely decrease by 15% to $12 billion in q1 of 2026.',
 'in q3 of 2024, olivia brown from johnson & johnson, envisions that the operating income will rise from $10 billion to $15 billion in 2028.',
 'kevin white, a financial expert, predicts on 10/10/2024 that the revenue at at&t may increase by $5 billion to $20 billion in 2027.',
 'according to a top executive from intel, on 2024-07-25, the net profit is expected to increase beyond $12 billion in the timeframe of q2 of 2029.',
 "in 2026-08-25, the stock price at mcdonald's is expected to be $200 per share, which is a 25% increase, as predicted by sophia rodriguez, a financial analyst, on 25 july 2024.",
 'on 2024-10-15, dr. rachel kim, a senior meteorologist at the national oceanic and atmospheric administration, forecasts that the precipitation levels in los angeles will likely increase by 15% in q2 of 2026.',
 'in 2024-08, emily chen from the european centre for medium-range weather forecasts envisions that the humidity in beijing should decrease by 12% in 2027-03.',
 'michael davis, a weather expert from the meteorological office, predicts on 2024-09-20 that the temperature in sydney will fall by 8°c in the timeframe of 2025-09.',
 'according to a top executive from the world meteorological organization, on 2024-11-01, the wind speed in tokyo is expected to rise beyond 20 mph in the timeframe of 2026-06.',
 'in 2028-02, the average sea level in miami has a probability of 10% to increase by 2 inches, as predicted by dr. lisa nguyen, a weather analyst from the national weather service, on 2024-07-15.',
 'on 2024-12-25, james lee, a weather reporter from the korean meteorological administration, forecasts that the snowfall levels in new york city will likely decrease by 5 inches in q1 of 2027.',
 'in 2025-01, david taylor from the australian bureau of meteorology predicts that the air quality index in melbourne will improve by 15% in 2026-10.',
 'dr. sophia patel, a weather expert from the indian meteorological department, predicts on 2024-06-01 that the temperature in mumbai will rise by 5°c in the timeframe of 2027-05.',
 'according to a senior meteorologist from the chinese meteorological administration, on 2024-03-15, the rainfall in shanghai is expected to increase beyond 20% in the timeframe of 2026-08.',
 'in 2029-04, the wind chill in chicago has a probability of 12% to decrease by 8°f, as predicted by dr. kevin white, a weather analyst from the national centers for environmental prediction, on 2024-02-20.',
 'on 2024-10-15, dr. david lee, a health expert, predicts that the average blood pressure at the american heart association will likely decrease by 10% in q2 of 2026.',
 'in 2024, dr. maria rodriguez from the world health organization envisions that the global life expectancy may rise from 72 to 75 years in 2028.',
 'dr. john smith predicts on 08/20/2024 that the prevalence of mental health disorders in the united states should stay stable at 20% in 2027.',
 'according to a report by dr. emily chen from the centers for disease control and prevention, on 21 aug 2024, the obesity rate among children is expected to increase beyond 25% in the timeframe of q4 of 2029.',
 'in q1 of 2025, the average daily step count in australia is expected to rise by 15%, as predicted by dr. michael brown from the national institutes of health on 2024-10-10.',
 'on 2024/11/12, dr. sophia patel, a health analyst, forecasts that the cancer survival rate at the mayo clinic will likely increase by 12% in 2026.',
 'in 2025, dr. kevin white from the american cancer society predicts that the average daily caloric intake may fall from 2500 to 2000 calories in quarter 2 of 2028.',
 'dr. lisa nguyen predicts on 2024-08-25 that the global vaccination rate for influenza in the european union should increase by 15% in 2027.',
 'according to a report by dr. daniel kim from the university of california, on 10/15/2024, the prevalence of chronic diseases among adults is expected to decrease beyond 30% in the timeframe of q3 of 2030.',
 'in 2029-08-20, the average weekly exercise hours in canada is expected to rise by 20%, as predicted by dr. olivia martin from the canadian medical association on 2024/10/20.',
 'on 2024-10-15, policy expert, john smith, predicts that the stock price at goldman sachs will rise by 10% in q2 of 2026.',
 'in 2024, policy analyst, emily johnson, from the federal reserve, envisions that the interest rate will increase from 2% to 4% in 2028.',
 'policy senior level person, michael brown, predicts on 08/20/2024 that the gdp in the united states may stay stable at $20 trillion in 2027.',
 'according to a policy top executive, robert williams, from jpmorgan chase, on 2024-08-22, the number of bank branches is expected to decrease beyond 5,000 in the timeframe of q4 of 2029.',
 'in 2025-08-20, the inflation rate in the european union has a probability of 80% to reach 3%, as predicted by policy reporter, sarah lee, on 2024-10-10.',
 'on 2024/11/12, policy expert, david white, forecasts that the exchange rate at the european central bank will likely decrease by 5% in q1 of 2027.',
 'in q3 of 2024, policy analyst, kevin davis, from the international monetary fund, predicts that the unemployment rate will fall from 5% to 3% in 2026.',
 'policy senior level person, olivia martinez, predicts on 2024-09-18 that the national debt in japan may increase by 10% in 2028.',
 'according to a policy top executive, james wilson, from citigroup, on 2024-10-25, the number of credit card holders is expected to rise beyond 100 million in the timeframe of q2 of 2030.',
 'in q4 of 2027, the number of initial public offerings in the united states is expected to be 500, which is a 20% increase, as predicted by policy analyst, daniel kim, on 2024-08-15.']

In [7]:
initialize_spacy = DataProcessing.setup_spacy()

### Word

In [ ]:
word_leveL_disable_components = ["lemmatizer"]
word_level_pos_tags, word_level_pos_mappings, word_level_ner_entities, word_level_ner_mappings = DataProcessing.extract_entities(only_predictions, initialize_spacy, word_leveL_disable_components)

In [9]:
word_level_pos_tags

{'ADJ',
 'ADP',
 'ADV',
 'AUX',
 'CCONJ',
 'DET',
 'NOUN',
 'NUM',
 'PART',
 'PRON',
 'PROPN',
 'PUNCT',
 'SCONJ',
 'SYM',
 'VERB'}

In [10]:
type(word_level_pos_mappings[0][0])

tuple

In [11]:
# ['on 2024-10-15, rachel patel, a financial analyst, predicts that the operating cash flow at general motors will likely decrease by $5 billion to $10 billion in q2 of 2026.',
# ['on 2024-10-15,  patel, a financial analyst, predicts that  operating cash flow at  motors    by 5 billion to $10 billion in   .',

"to" isn't in "on 2024-10-15, rachel patel, a financial analyst, predicts that the operating cash flow at general motors will likely decrease by $5 billion to $10 billion in q2 of 2026."

In [12]:
all_word_level_pos_df = DataProcessing.convert_to_df(word_level_pos_tags, mapping=word_level_pos_mappings)
all_word_level_pos_df

,SCONJ,ADJ,NUM,PART,VERB,AUX,ADV,PRON,DET,NOUN,PROPN,CCONJ,SYM,ADP,PUNCT
0,that,general,2026,to,decrease,will,likely,NaN,the,q2,rachel,NaN,$,of,.
1,that,julian,2028,to,rise,will,NaN,NaN,the,share,america,NaN,$,in,.
2,that,stable,2029,NaN,stay,may,NaN,NaN,the,pfizer,wilson,and,$,in,.
3,NaN,net,2027,to,increase,is,NaN,NaN,the,timeframe,q4,NaN,$,of,.
4,NaN,financial,2024,to,predicted,is,NaN,NaN,a,reporter,oct,NaN,$,on,.
5,that,gross,2026,to,decrease,will,likely,NaN,the,%,q1,NaN,$,of,.
6,that,olivia,2028,to,rise,will,NaN,NaN,the,income,johnson,&,$,in,.
7,that,financial,2027,to,increase,may,NaN,NaN,the,revenue,at&t,NaN,$,in,.
8,NaN,net,2029,to,increase,is,NaN,NaN,the,q2,intel,NaN,$,of,.
9,NaN,financial,2024,to,predicted,is,NaN,NaN,a,analyst,july,NaN,$,on,.
10,that,atmospheric,2026,NaN,increase,will,likely,NaN,the,q2,angeles,and,-,of,.
11,that,medium,03,NaN,decrease,should,emily,NaN,the,%,beijing,NaN,-,in,.
12,that,meteorological,09,NaN,fall,will,NaN,NaN,the,timeframe,c,NaN,-,of,.
13,NaN,meteorological,06,to,rise,is,NaN,NaN,the,timeframe,tokyo,NaN,-,of,.
14,NaN,national,15,to,predicted,has,NaN,NaN,the,service,nguyen,NaN,-,on,.
15,that,meteorological,2027,NaN,decrease,will,likely,NaN,the,inches,q1,NaN,-,of,.
16,that,australian,10,NaN,improve,will,NaN,NaN,the,%,meteorology,NaN,-,in,.
17,that,NaN,05,NaN,rise,will,NaN,NaN,the,timeframe,c,NaN,-,of,.
18,NaN,meteorological,08,to,increase,is,NaN,NaN,the,timeframe,shanghai,NaN,-,of,.
19,NaN,environmental,20,to,predicted,has,NaN,NaN,the,prediction,white,NaN,-,on,.
20,that,average,2026,NaN,decrease,will,likely,NaN,the,q2,american,NaN,-,of,.
21,that,global,2028,to,rise,may,NaN,NaN,the,years,rodriguez,NaN,NaN,in,.
22,that,stable,2027,NaN,stay,should,NaN,NaN,the,%,states,NaN,NaN,in,.
23,NaN,NaN,2029,to,increase,is,NaN,NaN,the,timeframe,q4,and,NaN,of,.
24,NaN,daily,10,to,predicted,is,NaN,NaN,the,health,institutes,NaN,-,on,.
25,that,NaN,2026,NaN,increase,will,likely,NaN,the,%,mayo,NaN,NaN,in,.
26,that,daily,2028,NaN,fall,may,NaN,NaN,the,quarter,white,NaN,NaN,of,.
27,NaN,global,2027,NaN,increase,should,NaN,that,the,%,union,NaN,-,in,.
28,NaN,chronic,2030,to,decrease,is,NaN,NaN,the,timeframe,q3,NaN,NaN,of,.
29,NaN,medical,20,to,predicted,is,NaN,NaN,the,association,2024/10/20,NaN,-,on,.
30,that,NaN,2026,NaN,rise,will,NaN,NaN,the,q2,smith,NaN,-,of,.
31,that,NaN,2028,to,increase,will,NaN,NaN,the,%,reserve,NaN,NaN,in,.
32,that,stable,2027,NaN,stay,may,NaN,NaN,the,gdp,states,NaN,$,in,.
33,NaN,top,2029,to,decrease,is,NaN,NaN,the,timeframe,q4,NaN,-,of,.
34,NaN,NaN,10,to,predicted,has,NaN,NaN,a,reporter,lee,NaN,-,on,.
35,that,NaN,2027,NaN,decrease,will,likely,NaN,the,%,q1,NaN,NaN,of,.
36,that,monetary,2026,to,fall,will,NaN,NaN,the,%,davis,NaN,NaN,in,.
37,that,national,2028,NaN,increase,may,NaN,NaN,the,%,japan,NaN,-,in,.
38,NaN,top,2030,to,rise,is,NaN,NaN,the,q2,wilson,NaN,-,of,.
39,NaN,public,15,to,predicted,is,NaN,NaN,a,analyst,kim,NaN,-,on,.

In [13]:
drop_word_level_pos_columns = ['PRON', 'DET', 'ADP', 'SCONJ', 'CCONJ', 'PUNCT', 'PART']
core_word_level_pos_df = DataProcessing.drop_df_columns(all_word_level_pos_df, drop_word_level_pos_columns)
core_word_level_pos_df

,ADJ,NUM,VERB,AUX,ADV,NOUN,PROPN,SYM
0,general,2026,decrease,will,likely,q2,rachel,$
1,julian,2028,rise,will,NaN,share,america,$
2,stable,2029,stay,may,NaN,pfizer,wilson,$
3,net,2027,increase,is,NaN,timeframe,q4,$
4,financial,2024,predicted,is,NaN,reporter,oct,$
5,gross,2026,decrease,will,likely,%,q1,$
6,olivia,2028,rise,will,NaN,income,johnson,$
7,financial,2027,increase,may,NaN,revenue,at&t,$
8,net,2029,increase,is,NaN,q2,intel,$
9,financial,2024,predicted,is,NaN,analyst,july,$
10,atmospheric,2026,increase,will,likely,q2,angeles,-
11,medium,03,decrease,should,emily,%,beijing,-
12,meteorological,09,fall,will,NaN,timeframe,c,-
13,meteorological,06,rise,is,NaN,timeframe,tokyo,-
14,national,15,predicted,has,NaN,service,nguyen,-
15,meteorological,2027,decrease,will,likely,inches,q1,-
16,australian,10,improve,will,NaN,%,meteorology,-
17,NaN,05,rise,will,NaN,timeframe,c,-
18,meteorological,08,increase,is,NaN,timeframe,shanghai,-
19,environmental,20,predicted,has,NaN,prediction,white,-
20,average,2026,decrease,will,likely,q2,american,-
21,global,2028,rise,may,NaN,years,rodriguez,NaN
22,stable,2027,stay,should,NaN,%,states,NaN
23,NaN,2029,increase,is,NaN,timeframe,q4,NaN
24,daily,10,predicted,is,NaN,health,institutes,-
25,NaN,2026,increase,will,likely,%,mayo,NaN
26,daily,2028,fall,may,NaN,quarter,white,NaN
27,global,2027,increase,should,NaN,%,union,-
28,chronic,2030,decrease,is,NaN,timeframe,q3,NaN
29,medical,20,predicted,is,NaN,association,2024/10/20,-
30,NaN,2026,rise,will,NaN,q2,smith,-
31,NaN,2028,increase,will,NaN,%,reserve,NaN
32,stable,2027,stay,may,NaN,gdp,states,$
33,top,2029,decrease,is,NaN,timeframe,q4,-
34,NaN,10,predicted,has,NaN,reporter,lee,-
35,NaN,2027,decrease,will,likely,%,q1,NaN
36,monetary,2026,fall,will,NaN,%,davis,NaN
37,national,2028,increase,may,NaN,%,japan,-
38,top,2030,rise,is,NaN,q2,wilson,-
39,public,15,predicted,is,NaN,analyst,kim,-

In [15]:
encoded_word_level_pos_df = DataProcessing.encode_tags_entities_dataframe(core_word_level_pos_df)
encoded_word_level_pos_df

    ADJ  NUM  VERB  AUX  ADV  NOUN  PROPN  SYM
0     1    1     1    1    1     1      1    1
1     1    1     1    1    0     1      1    1
2     1    1     1    1    0     1      1    1
3     1    1     1    1    0     1      1    1
4     1    1     1    1    0     1      1    1
5     1    1     1    1    1     1      1    1
6     1    1     1    1    0     1      1    1
7     1    1     1    1    0     1      1    1
8     1    1     1    1    0     1      1    1
9     1    1     1    1    0     1      1    1
10    1    1     1    1    1     1      1    1
11    1    1     1    1    1     1      1    1
12    1    1     1    1    0     1      1    1
13    1    1     1    1    0     1      1    1
14    1    1     1    1    0     1      1    1
15    1    1     1    1    1     1      1    1
16    1    1     1    1    0     1      1    1
17    0    1     1    1    0     1      1    1
18    1    1     1    1    0     1      1    1
19    1    1     1    1    0     1      1    1
20    1    1     1    1    1     1      1    1
21    1    1     1    1    0     1      1    0
22    1    1     1    1    0     1      1    0
23    0    1     1    1    0     1      1    0
24    1    1     1    1    0     1      1    1
25    0    1     1    1    1     1      1    0
26    1    1     1    1    0     1      1    0
27    1    1     1    1    0     1      1    1
28    1    1     1    1    0     1      1    0
29    1    1     1    1    0     1      1    1
30    0    1     1    1    0     1      1    1
31    0    1     1    1    0     1      1    0
32    1    1     1    1    0     1      1    1
33    1    1     1    1    0     1      1    1
34    0    1     1    1    0     1      1    1
35    0    1     1    1    1     1      1    0
36    1    1     1    1    0     1      1    0
37    1    1     1    1    0     1      1    1
38    1    1     1    1    0     1      1    1
39    1    1     1    1    0     1      1    1

In [17]:
all_word_level_ner_df = DataProcessing.convert_tags_entities_to_dataframe(word_level_ner_entities, word_level_ner_mappings)
all_word_level_ner_df

,DATE_1,PERSON_2,CARDINAL_1,MONEY_1,ORG_1,PERCENT_1,PERCENT_2,QUANTITY_1,DATE_3,GPE_1,NORP_1,DATE_2,PERSON_1,DATE_4
0,2024-10-15,NaN,NaN,$5 billion to $10 billion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,rachel patel,NaN
1,2024,NaN,NaN,$50 to $75,bank of america,NaN,NaN,NaN,NaN,NaN,NaN,2028,julian sanchez,NaN
2,20/08/2024,NaN,NaN,$15 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029,emily wilson,NaN
3,2027,NaN,2024/08/20,$8 billion,NaN,NaN,NaN,NaN,NaN,cisco,NaN,NaN,NaN,NaN
4,2025-02-18,NaN,NaN,$25 billion,NaN,20 percent,10%,NaN,NaN,NaN,NaN,15 oct 2024,david lee,NaN
5,"wednesday, november 20, 2024",NaN,3,$12 billion,NaN,15%,NaN,NaN,NaN,NaN,NaN,2026,michael davis,NaN
6,q3 of 2024,NaN,NaN,$10 billion to $15 billion,johnson & johnson,NaN,NaN,NaN,NaN,NaN,NaN,2028,NaN,NaN
7,10/10/2024,NaN,NaN,$5 billion to $20 billion,at&t,NaN,NaN,NaN,NaN,NaN,NaN,2027,kevin white,NaN
8,2024-07-25,NaN,NaN,$12 billion,intel,NaN,NaN,NaN,NaN,NaN,NaN,2029,NaN,NaN
9,2026-08-25,NaN,NaN,200,mcdonald's,25%,NaN,NaN,NaN,NaN,NaN,25 july 2024,NaN,NaN
10,2024-10-15,NaN,NaN,NaN,NaN,15%,NaN,NaN,NaN,los angeles,NaN,2026,rachel kim,NaN
11,2024-08,NaN,NaN,NaN,the european centre,12%,NaN,NaN,NaN,beijing,NaN,2027-03,NaN,NaN
12,2024-09-20,NaN,8°,NaN,NaN,NaN,NaN,NaN,NaN,sydney,NaN,2025-09,michael davis,NaN
13,2024-11-01,NaN,NaN,NaN,NaN,NaN,NaN,20 mph,NaN,tokyo,NaN,2026-06,NaN,NaN
14,2028-02,NaN,NaN,NaN,NaN,10%,NaN,2 inches,NaN,miami,NaN,2024-07-15,lisa nguyen,NaN
15,2024-12-25,NaN,NaN,NaN,NaN,NaN,NaN,5 inches,NaN,new york city,korean,2027,james lee,NaN
16,2025-01,NaN,NaN,NaN,the australian bureau,15%,NaN,NaN,NaN,NaN,NaN,2026-10,david taylor,NaN
17,2024-06-01,NaN,5°,NaN,NaN,NaN,NaN,NaN,NaN,mumbai,indian,2027-05,sophia patel,NaN
18,2024-03-15,NaN,NaN,NaN,NaN,20%,NaN,NaN,NaN,shanghai,chinese,2026-08,NaN,NaN
19,2029-04,NaN,8°f,NaN,NaN,12%,NaN,NaN,NaN,chicago,NaN,2024-02-20,kevin white,NaN
20,2024-10-15,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,NaN,american,2026,david lee,NaN
21,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2028,NaN,NaN,72 to 75 years,maria,NaN
22,2027,john smith,NaN,NaN,NaN,20%,NaN,NaN,NaN,the united states,NaN,NaN,dr.,NaN
23,2024,NaN,21,NaN,NaN,25%,NaN,NaN,NaN,NaN,NaN,2029,emily chen,NaN
24,2025,NaN,NaN,NaN,NaN,15%,NaN,NaN,2024-10-10,australia,NaN,daily,michael brown,NaN
25,2024/11/12,NaN,NaN,NaN,the mayo clinic,12%,NaN,NaN,NaN,NaN,NaN,2026,sophia patel,NaN
26,2025,NaN,2500 to,NaN,NaN,NaN,NaN,NaN,2000,NaN,american,daily,kevin white,quarter 2 of 2028
27,2024-08-25,lisa nguyen,NaN,NaN,the european union,15%,NaN,NaN,NaN,NaN,NaN,2027,dr.,NaN
28,10/15/2024,NaN,NaN,NaN,the university of california,30%,NaN,NaN,NaN,NaN,NaN,2030,daniel kim,NaN
29,2029-08-20,olivia martin,2024/10/20,NaN,the canadian medical association,20%,NaN,NaN,NaN,canada,NaN,weekly,dr.,NaN
30,2024-10-15,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,NaN,NaN,2026,john smith,NaN
31,2024,NaN,NaN,NaN,the federal reserve,2% to 4%,NaN,NaN,NaN,NaN,NaN,2028,emily johnson,NaN
32,2027,NaN,NaN,$20 trillion,NaN,NaN,NaN,NaN,NaN,the united states,NaN,NaN,michael brown,NaN
33,2024-08-22,NaN,"5,000",NaN,jpmorgan chase,NaN,NaN,NaN,NaN,NaN,NaN,2029,robert williams,NaN
34,2025-08-20,NaN,NaN,NaN,the european union,80%,3%,NaN,NaN,NaN,NaN,2024-10-10,sarah lee,NaN
35,2024/11/12,NaN,NaN,NaN,the european central bank,5%,NaN,NaN,NaN,NaN,NaN,2027,david white,NaN
36,q3 of 2024,NaN,NaN,NaN,NaN,5% to 3%,NaN,NaN,NaN,NaN,NaN,2026,kevin davis,NaN
37,2024-09-18,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,japan,NaN,2028,olivia martinez,NaN
38,2024-10-25,NaN,100 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2030,james wilson,NaN
39,2027,NaN,500,NaN,NaN,20%,NaN,NaN,NaN,the united states,NaN,2024-08-15,daniel kim,NaN

In [ ]:
# Do not want to drop any

# drop_word_level_ner_columns = None
# core_word_level_ner_df = DataProcessing.drop_df_columns(all_word_level_ner_df, drop_word_level_pos_columns)
# core_word_level_ner_df

In [19]:
encoded_word_level_ner_df = DataProcessing.encode_tags_entities_dataframe(all_word_level_ner_df)
encoded_word_level_ner_df

,DATE_1,PERSON_2,CARDINAL_1,MONEY_1,ORG_1,PERCENT_1,PERCENT_2,QUANTITY_1,DATE_3,GPE_1,NORP_1,DATE_2,PERSON_1,DATE_4
0,1,0,0,1,0,0,0,0,0,0,0,1,1,0
1,1,0,0,1,1,0,0,0,0,0,0,1,1,0
2,1,0,0,1,0,0,0,0,0,0,0,1,1,0
3,1,0,1,1,0,0,0,0,0,1,0,0,0,0
4,1,0,0,1,0,1,1,0,0,0,0,1,1,0
5,1,0,1,1,0,1,0,0,0,0,0,1,1,0
6,1,0,0,1,1,0,0,0,0,0,0,1,0,0
7,1,0,0,1,1,0,0,0,0,0,0,1,1,0
8,1,0,0,1,1,0,0,0,0,0,0,1,0,0
9,1,0,0,1,1,1,0,0,0,0,0,1,0,0
10,1,0,0,0,0,1,0,0,0,1,0,1,1,0
11,1,0,0,0,1,1,0,0,0,1,0,1,0,0
12,1,0,1,0,0,0,0,0,0,1,0,1,1,0
13,1,0,0,0,0,0,0,1,0,1,0,1,0,0
14,1,0,0,0,0,1,0,1,0,1,0,1,1,0
15,1,0,0,0,0,0,0,1,0,1,1,1,1,0
16,1,0,0,0,1,1,0,0,0,0,0,1,1,0
17,1,0,1,0,0,0,0,0,0,1,1,1,1,0
18,1,0,0,0,0,1,0,0,0,1,1,1,0,0
19,1,0,1,0,0,1,0,0,0,1,0,1,1,0
20,1,0,0,0,0,1,0,0,0,0,1,1,1,0
21,1,0,0,0,0,0,0,0,1,0,0,1,1,0
22,1,1,0,0,0,1,0,0,0,1,0,0,1,0
23,1,0,1,0,0,1,0,0,0,0,0,1,1,0
24,1,0,0,0,0,1,0,0,1,1,0,1,1,0
25,1,0,0,0,1,1,0,0,0,0,0,1,1,0
26,1,0,1,0,0,0,0,0,1,0,1,1,1,1
27,1,1,0,0,1,1,0,0,0,0,0,1,1,0
28,1,0,0,0,1,1,0,0,0,0,0,1,1,0
29,1,1,1,0,1,1,0,0,0,1,0,1,1,0
30,1,0,0,0,0,1,0,0,0,0,0,1,1,0
31,1,0,0,0,1,1,0,0,0,0,0,1,1,0
32,1,0,0,1,0,0,0,0,0,1,0,0,1,0
33,1,0,1,0,1,0,0,0,0,0,0,1,1,0
34,1,0,0,0,1,1,1,0,0,0,0,1,1,0
35,1,0,0,0,1,1,0,0,0,0,0,1,1,0
36,1,0,0,0,0,1,0,0,0,0,0,1,1,0
37,1,0,0,0,0,1,0,0,0,1,0,1,1,0
38,1,0,1,0,0,0,0,0,0,0,0,1,1,0
39,1,0,1,0,0,1,0,0,0,1,0,1,1,0

In [18]:
word_level_tags_entities = [all_word_level_pos_df, all_word_level_ner_df]
word_level_tags_entities_df = DataProcessing.concat_dfs(word_level_tags_entities, axis=1, ignore_index=False)
word_level_tags_entities_df

,SCONJ,ADJ,NUM,PART,VERB,AUX,ADV,PRON,DET,NOUN,...,ORG_1,PERCENT_1,PERCENT_2,QUANTITY_1,DATE_3,GPE_1,NORP_1,DATE_2,PERSON_1,DATE_4
0,that,general,2026,to,decrease,will,likely,NaN,the,q2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,rachel patel,NaN
1,that,julian,2028,to,rise,will,NaN,NaN,the,share,...,bank of america,NaN,NaN,NaN,NaN,NaN,NaN,2028,julian sanchez,NaN
2,that,stable,2029,NaN,stay,may,NaN,NaN,the,pfizer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029,emily wilson,NaN
3,NaN,net,2027,to,increase,is,NaN,NaN,the,timeframe,...,NaN,NaN,NaN,NaN,NaN,cisco,NaN,NaN,NaN,NaN
4,NaN,financial,2024,to,predicted,is,NaN,NaN,a,reporter,...,NaN,20 percent,10%,NaN,NaN,NaN,NaN,15 oct 2024,david lee,NaN
5,that,gross,2026,to,decrease,will,likely,NaN,the,%,...,NaN,15%,NaN,NaN,NaN,NaN,NaN,2026,michael davis,NaN
6,that,olivia,2028,to,rise,will,NaN,NaN,the,income,...,johnson & johnson,NaN,NaN,NaN,NaN,NaN,NaN,2028,NaN,NaN
7,that,financial,2027,to,increase,may,NaN,NaN,the,revenue,...,at&t,NaN,NaN,NaN,NaN,NaN,NaN,2027,kevin white,NaN
8,NaN,net,2029,to,increase,is,NaN,NaN,the,q2,...,intel,NaN,NaN,NaN,NaN,NaN,NaN,2029,NaN,NaN
9,NaN,financial,2024,to,predicted,is,NaN,NaN,a,analyst,...,mcdonald's,25%,NaN,NaN,NaN,NaN,NaN,25 july 2024,NaN,NaN
10,that,atmospheric,2026,NaN,increase,will,likely,NaN,the,q2,...,NaN,15%,NaN,NaN,NaN,los angeles,NaN,2026,rachel kim,NaN
11,that,medium,03,NaN,decrease,should,emily,NaN,the,%,...,the european centre,12%,NaN,NaN,NaN,beijing,NaN,2027-03,NaN,NaN
12,that,meteorological,09,NaN,fall,will,NaN,NaN,the,timeframe,...,NaN,NaN,NaN,NaN,NaN,sydney,NaN,2025-09,michael davis,NaN
13,NaN,meteorological,06,to,rise,is,NaN,NaN,the,timeframe,...,NaN,NaN,NaN,20 mph,NaN,tokyo,NaN,2026-06,NaN,NaN
14,NaN,national,15,to,predicted,has,NaN,NaN,the,service,...,NaN,10%,NaN,2 inches,NaN,miami,NaN,2024-07-15,lisa nguyen,NaN
15,that,meteorological,2027,NaN,decrease,will,likely,NaN,the,inches,...,NaN,NaN,NaN,5 inches,NaN,new york city,korean,2027,james lee,NaN
16,that,australian,10,NaN,improve,will,NaN,NaN,the,%,...,the australian bureau,15%,NaN,NaN,NaN,NaN,NaN,2026-10,david taylor,NaN
17,that,NaN,05,NaN,rise,will,NaN,NaN,the,timeframe,...,NaN,NaN,NaN,NaN,NaN,mumbai,indian,2027-05,sophia patel,NaN
18,NaN,meteorological,08,to,increase,is,NaN,NaN,the,timeframe,...,NaN,20%,NaN,NaN,NaN,shanghai,chinese,2026-08,NaN,NaN
19,NaN,environmental,20,to,predicted,has,NaN,NaN,the,prediction,...,NaN,12%,NaN,NaN,NaN,chicago,NaN,2024-02-20,kevin white,NaN
20,that,average,2026,NaN,decrease,will,likely,NaN,the,q2,...,NaN,10%,NaN,NaN,NaN,NaN,american,2026,david lee,NaN
21,that,global,2028,to,rise,may,NaN,NaN,the,years,...,NaN,NaN,NaN,NaN,2028,NaN,NaN,72 to 75 years,maria,NaN
22,that,stable,2027,NaN,stay,should,NaN,NaN,the,%,...,NaN,20%,NaN,NaN,NaN,the united states,NaN,NaN,dr.,NaN
23,NaN,NaN,2029,to,increase,is,NaN,NaN,the,timeframe,...,NaN,25%,NaN,NaN,NaN,NaN,NaN,2029,emily chen,NaN
24,NaN,daily,10,to,predicted,is,NaN,NaN,the,health,...,NaN,15%,NaN,NaN,2024-10-10,australia,NaN,daily,michael brown,NaN
25,that,NaN,2026,NaN,increase,will,likely,NaN,the,%,...,the mayo clinic,12%,NaN,NaN,NaN,NaN,NaN,2026,sophia patel,NaN
26,that,daily,2028,NaN,fall,may,NaN,NaN,the,quarter,...,NaN,NaN,NaN,NaN,2000,NaN,american,daily,kevin white,quarter 2 of 2028
27,NaN,global,2027,NaN,increase,should,NaN,that,the,%,...,the european union,15%,NaN,NaN,NaN,NaN,NaN,2027,dr.,NaN
28,NaN,chronic,2030,to,decrease,is,NaN,NaN,the,timeframe,...,the university of california,30%,NaN,NaN,NaN,NaN,NaN,2030,daniel kim,NaN
29,NaN,medical,20,to,predicted,is,NaN,NaN,the,association,...,the canadian medical association,20%,NaN,NaN,NaN,canada,NaN,weekly,dr.,NaN
30,that,NaN,2026,NaN,rise,will,NaN,NaN,the,q2,...,NaN,10%,NaN,NaN,NaN,NaN,NaN,2026,john smith,NaN
31,that,NaN,2028,to,increase,will,NaN,NaN,the,%,...,the federal reserve,2% to 4%,NaN,NaN,NaN,NaN,NaN,2028,emily johnson,NaN
32,that,stable,2027,NaN,stay,may,NaN,NaN,the,gdp,...,NaN,NaN,NaN,NaN,NaN,the united states,NaN,NaN,michael brown,NaN
33,NaN,top,2029,to,decrease,is,NaN,NaN,the,timeframe,...,jpmorgan chase,NaN,NaN,NaN,NaN,NaN,NaN,2029,robert williams,NaN
34,NaN,NaN,10,to,predicted,has,NaN,NaN,a,reporter,...,the european union,80%,3%,NaN,NaN,NaN,NaN,2024-10-10,sarah lee,NaN
35,that,NaN,2027,NaN,decrease,will,likely,NaN,the,%,...,the european central bank,5%,NaN,NaN,NaN,NaN,NaN,2027,david white,NaN
36,that,monetary,2026,to,fall,will,NaN,NaN,the,%,...,NaN,5% to 3%,NaN,NaN,NaN,NaN,NaN,2026,kevin davis,NaN
37,that,national,2028,NaN,increase,may,NaN,NaN,the,%,...,NaN,10%,NaN,NaN,NaN,japan,NaN,2028,olivia martinez,NaN
38,NaN,top,2030,to,rise,is,NaN,NaN,the,q2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2030,james wilson,NaN
39,NaN,public,15,to,predicted,is,NaN,NaN,a,analyst,...,NaN,20%,NaN,NaN,NaN,the united states,NaN,2024-08-15,daniel kim,NaN

In [20]:
encoded_word_level_tags_entities_df = DataProcessing.encode_tags_entities_dataframe(word_level_tags_entities_df)
encoded_word_level_tags_entities_df

,SCONJ,ADJ,NUM,PART,VERB,AUX,ADV,PRON,DET,NOUN,...,ORG_1,PERCENT_1,PERCENT_2,QUANTITY_1,DATE_3,GPE_1,NORP_1,DATE_2,PERSON_1,DATE_4
0,1,1,1,1,1,1,1,0,1,1,...,0,0,0,0,0,0,0,1,1,0
1,1,1,1,1,1,1,0,0,1,1,...,1,0,0,0,0,0,0,1,1,0
2,1,1,1,0,1,1,0,0,1,1,...,0,0,0,0,0,0,0,1,1,0
3,0,1,1,1,1,1,0,0,1,1,...,0,0,0,0,0,1,0,0,0,0
4,0,1,1,1,1,1,0,0,1,1,...,0,1,1,0,0,0,0,1,1,0
5,1,1,1,1,1,1,1,0,1,1,...,0,1,0,0,0,0,0,1,1,0
6,1,1,1,1,1,1,0,0,1,1,...,1,0,0,0,0,0,0,1,0,0
7,1,1,1,1,1,1,0,0,1,1,...,1,0,0,0,0,0,0,1,1,0
8,0,1,1,1,1,1,0,0,1,1,...,1,0,0,0,0,0,0,1,0,0
9,0,1,1,1,1,1,0,0,1,1,...,1,1,0,0,0,0,0,1,0,0
10,1,1,1,0,1,1,1,0,1,1,...,0,1,0,0,0,1,0,1,1,0
11,1,1,1,0,1,1,1,0,1,1,...,1,1,0,0,0,1,0,1,0,0
12,1,1,1,0,1,1,0,0,1,1,...,0,0,0,0,0,1,0,1,1,0
13,0,1,1,1,1,1,0,0,1,1,...,0,0,0,1,0,1,0,1,0,0
14,0,1,1,1,1,1,0,0,1,1,...,0,1,0,1,0,1,0,1,1,0
15,1,1,1,0,1,1,1,0,1,1,...,0,0,0,1,0,1,1,1,1,0
16,1,1,1,0,1,1,0,0,1,1,...,1,1,0,0,0,0,0,1,1,0
17,1,0,1,0,1,1,0,0,1,1,...,0,0,0,0,0,1,1,1,1,0
18,0,1,1,1,1,1,0,0,1,1,...,0,1,0,0,0,1,1,1,0,0
19,0,1,1,1,1,1,0,0,1,1,...,0,1,0,0,0,1,0,1,1,0
20,1,1,1,0,1,1,1,0,1,1,...,0,1,0,0,0,0,1,1,1,0
21,1,1,1,1,1,1,0,0,1,1,...,0,0,0,0,1,0,0,1,1,0
22,1,1,1,0,1,1,0,0,1,1,...,0,1,0,0,0,1,0,0,1,0
23,0,0,1,1,1,1,0,0,1,1,...,0,1,0,0,0,0,0,1,1,0
24,0,1,1,1,1,1,0,0,1,1,...,0,1,0,0,1,1,0,1,1,0
25,1,0,1,0,1,1,1,0,1,1,...,1,1,0,0,0,0,0,1,1,0
26,1,1,1,0,1,1,0,0,1,1,...,0,0,0,0,1,0,1,1,1,1
27,0,1,1,0,1,1,0,1,1,1,...,1,1,0,0,0,0,0,1,1,0
28,0,1,1,1,1,1,0,0,1,1,...,1,1,0,0,0,0,0,1,1,0
29,0,1,1,1,1,1,0,0,1,1,...,1,1,0,0,0,1,0,1,1,0
30,1,0,1,0,1,1,0,0,1,1,...,0,1,0,0,0,0,0,1,1,0
31,1,0,1,1,1,1,0,0,1,1,...,1,1,0,0,0,0,0,1,1,0
32,1,1,1,0,1,1,0,0,1,1,...,0,0,0,0,0,1,0,0,1,0
33,0,1,1,1,1,1,0,0,1,1,...,1,0,0,0,0,0,0,1,1,0
34,0,0,1,1,1,1,0,0,1,1,...,1,1,1,0,0,0,0,1,1,0
35,1,0,1,0,1,1,1,0,1,1,...,1,1,0,0,0,0,0,1,1,0
36,1,1,1,1,1,1,0,0,1,1,...,0,1,0,0,0,0,0,1,1,0
37,1,1,1,0,1,1,0,0,1,1,...,0,1,0,0,0,1,0,1,1,0
38,0,1,1,1,1,1,0,0,1,1,...,0,0,0,0,0,0,0,1,1,0
39,0,1,1,1,1,1,0,0,1,1,...,0,1,0,0,0,1,0,1,1,0

- Need to clean. I don't think we're capturing all of the words for both POS and NER.

### Sentence

In [21]:
sentence_leveL_disable_components = ["tok2vec", "parser", "lemmatizer"]
sentence_level_pos_tags, sentence_level_pos_mappings, sentence_level_ner_entities, sentence_level_ner_mappings = DataProcessing.extract_entities(only_predictions, initialize_spacy, sentence_leveL_disable_components)

In [22]:
sentence_level_pos_tags

{'NOUN'}

In [23]:
sentence_level_pos_df = DataProcessing.convert_tags_entities_to_dataframe(sentence_level_pos_tags, sentence_level_pos_mappings)
sentence_level_pos_df

   NOUN
0     .
1     .
2     .
3     .
4     .
5     .
6     .
7     .
8     .
9     .
10    .
11    .
12    .
13    .
14    .
15    .
16    .
17    .
18    .
19    .
20    .
21    .
22    .
23    .
24    .
25    .
26    .
27    .
28    .
29    .
30    .
31    .
32    .
33    .
34    .
35    .
36    .
37    .
38    .
39    .

In [24]:
sentence_level_ner_df = DataProcessing.convert_tags_entities_to_dataframe(sentence_level_ner_entities, sentence_level_ner_mappings)
sentence_level_ner_df

,DATE_1,PERSON_2,CARDINAL_1,MONEY_1,ORG_1,PERCENT_1,PERCENT_2,QUANTITY_1,DATE_3,GPE_1,NORP_1,DATE_2,PERSON_1,DATE_4
0,2024-10-15,NaN,NaN,$5 billion to $10 billion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,rachel patel,NaN
1,2024,NaN,NaN,$50 to $75,bank of america,NaN,NaN,NaN,NaN,NaN,NaN,2028,julian sanchez,NaN
2,20/08/2024,NaN,NaN,$15 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029,emily wilson,NaN
3,2027,NaN,2024/08/20,$8 billion,NaN,NaN,NaN,NaN,NaN,cisco,NaN,NaN,NaN,NaN
4,2025-02-18,NaN,NaN,$25 billion,NaN,20 percent,10%,NaN,NaN,NaN,NaN,15 oct 2024,david lee,NaN
5,"wednesday, november 20, 2024",NaN,3,$12 billion,NaN,15%,NaN,NaN,NaN,NaN,NaN,2026,michael davis,NaN
6,q3 of 2024,NaN,NaN,$10 billion to $15 billion,johnson & johnson,NaN,NaN,NaN,NaN,NaN,NaN,2028,NaN,NaN
7,10/10/2024,NaN,NaN,$5 billion to $20 billion,at&t,NaN,NaN,NaN,NaN,NaN,NaN,2027,kevin white,NaN
8,2024-07-25,NaN,NaN,$12 billion,intel,NaN,NaN,NaN,NaN,NaN,NaN,2029,NaN,NaN
9,2026-08-25,NaN,NaN,200,mcdonald's,25%,NaN,NaN,NaN,NaN,NaN,25 july 2024,NaN,NaN
10,2024-10-15,NaN,NaN,NaN,NaN,15%,NaN,NaN,NaN,los angeles,NaN,2026,rachel kim,NaN
11,2024-08,NaN,NaN,NaN,the european centre,12%,NaN,NaN,NaN,beijing,NaN,2027-03,NaN,NaN
12,2024-09-20,NaN,8°,NaN,NaN,NaN,NaN,NaN,NaN,sydney,NaN,2025-09,michael davis,NaN
13,2024-11-01,NaN,NaN,NaN,NaN,NaN,NaN,20 mph,NaN,tokyo,NaN,2026-06,NaN,NaN
14,2028-02,NaN,NaN,NaN,NaN,10%,NaN,2 inches,NaN,miami,NaN,2024-07-15,lisa nguyen,NaN
15,2024-12-25,NaN,NaN,NaN,NaN,NaN,NaN,5 inches,NaN,new york city,korean,2027,james lee,NaN
16,2025-01,NaN,NaN,NaN,the australian bureau,15%,NaN,NaN,NaN,NaN,NaN,2026-10,david taylor,NaN
17,2024-06-01,NaN,5°,NaN,NaN,NaN,NaN,NaN,NaN,mumbai,indian,2027-05,sophia patel,NaN
18,2024-03-15,NaN,NaN,NaN,NaN,20%,NaN,NaN,NaN,shanghai,chinese,2026-08,NaN,NaN
19,2029-04,NaN,8°f,NaN,NaN,12%,NaN,NaN,NaN,chicago,NaN,2024-02-20,kevin white,NaN
20,2024-10-15,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,NaN,american,2026,david lee,NaN
21,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2028,NaN,NaN,72 to 75 years,maria,NaN
22,2027,john smith,NaN,NaN,NaN,20%,NaN,NaN,NaN,the united states,NaN,NaN,dr.,NaN
23,2024,NaN,21,NaN,NaN,25%,NaN,NaN,NaN,NaN,NaN,2029,emily chen,NaN
24,2025,NaN,NaN,NaN,NaN,15%,NaN,NaN,2024-10-10,australia,NaN,daily,michael brown,NaN
25,2024/11/12,NaN,NaN,NaN,the mayo clinic,12%,NaN,NaN,NaN,NaN,NaN,2026,sophia patel,NaN
26,2025,NaN,2500 to,NaN,NaN,NaN,NaN,NaN,2000,NaN,american,daily,kevin white,quarter 2 of 2028
27,2024-08-25,lisa nguyen,NaN,NaN,the european union,15%,NaN,NaN,NaN,NaN,NaN,2027,dr.,NaN
28,10/15/2024,NaN,NaN,NaN,the university of california,30%,NaN,NaN,NaN,NaN,NaN,2030,daniel kim,NaN
29,2029-08-20,olivia martin,2024/10/20,NaN,the canadian medical association,20%,NaN,NaN,NaN,canada,NaN,weekly,dr.,NaN
30,2024-10-15,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,NaN,NaN,2026,john smith,NaN
31,2024,NaN,NaN,NaN,the federal reserve,2% to 4%,NaN,NaN,NaN,NaN,NaN,2028,emily johnson,NaN
32,2027,NaN,NaN,$20 trillion,NaN,NaN,NaN,NaN,NaN,the united states,NaN,NaN,michael brown,NaN
33,2024-08-22,NaN,"5,000",NaN,jpmorgan chase,NaN,NaN,NaN,NaN,NaN,NaN,2029,robert williams,NaN
34,2025-08-20,NaN,NaN,NaN,the european union,80%,3%,NaN,NaN,NaN,NaN,2024-10-10,sarah lee,NaN
35,2024/11/12,NaN,NaN,NaN,the european central bank,5%,NaN,NaN,NaN,NaN,NaN,2027,david white,NaN
36,q3 of 2024,NaN,NaN,NaN,NaN,5% to 3%,NaN,NaN,NaN,NaN,NaN,2026,kevin davis,NaN
37,2024-09-18,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,japan,NaN,2028,olivia martinez,NaN
38,2024-10-25,NaN,100 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2030,james wilson,NaN
39,2027,NaN,500,NaN,NaN,20%,NaN,NaN,NaN,the united states,NaN,2024-08-15,daniel kim,NaN

In [25]:
sentence_level_tags_entities = [sentence_level_pos_df, sentence_level_ner_df]
sentence_level_tags_entities_df = DataProcessing.concat_dfs(sentence_level_tags_entities, axis=1, ignore_index=False)
sentence_level_tags_entities_df

,NOUN,DATE_1,PERSON_2,CARDINAL_1,MONEY_1,ORG_1,PERCENT_1,PERCENT_2,QUANTITY_1,DATE_3,GPE_1,NORP_1,DATE_2,PERSON_1,DATE_4
0,.,2024-10-15,NaN,NaN,$5 billion to $10 billion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026,rachel patel,NaN
1,.,2024,NaN,NaN,$50 to $75,bank of america,NaN,NaN,NaN,NaN,NaN,NaN,2028,julian sanchez,NaN
2,.,20/08/2024,NaN,NaN,$15 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2029,emily wilson,NaN
3,.,2027,NaN,2024/08/20,$8 billion,NaN,NaN,NaN,NaN,NaN,cisco,NaN,NaN,NaN,NaN
4,.,2025-02-18,NaN,NaN,$25 billion,NaN,20 percent,10%,NaN,NaN,NaN,NaN,15 oct 2024,david lee,NaN
5,.,"wednesday, november 20, 2024",NaN,3,$12 billion,NaN,15%,NaN,NaN,NaN,NaN,NaN,2026,michael davis,NaN
6,.,q3 of 2024,NaN,NaN,$10 billion to $15 billion,johnson & johnson,NaN,NaN,NaN,NaN,NaN,NaN,2028,NaN,NaN
7,.,10/10/2024,NaN,NaN,$5 billion to $20 billion,at&t,NaN,NaN,NaN,NaN,NaN,NaN,2027,kevin white,NaN
8,.,2024-07-25,NaN,NaN,$12 billion,intel,NaN,NaN,NaN,NaN,NaN,NaN,2029,NaN,NaN
9,.,2026-08-25,NaN,NaN,200,mcdonald's,25%,NaN,NaN,NaN,NaN,NaN,25 july 2024,NaN,NaN
10,.,2024-10-15,NaN,NaN,NaN,NaN,15%,NaN,NaN,NaN,los angeles,NaN,2026,rachel kim,NaN
11,.,2024-08,NaN,NaN,NaN,the european centre,12%,NaN,NaN,NaN,beijing,NaN,2027-03,NaN,NaN
12,.,2024-09-20,NaN,8°,NaN,NaN,NaN,NaN,NaN,NaN,sydney,NaN,2025-09,michael davis,NaN
13,.,2024-11-01,NaN,NaN,NaN,NaN,NaN,NaN,20 mph,NaN,tokyo,NaN,2026-06,NaN,NaN
14,.,2028-02,NaN,NaN,NaN,NaN,10%,NaN,2 inches,NaN,miami,NaN,2024-07-15,lisa nguyen,NaN
15,.,2024-12-25,NaN,NaN,NaN,NaN,NaN,NaN,5 inches,NaN,new york city,korean,2027,james lee,NaN
16,.,2025-01,NaN,NaN,NaN,the australian bureau,15%,NaN,NaN,NaN,NaN,NaN,2026-10,david taylor,NaN
17,.,2024-06-01,NaN,5°,NaN,NaN,NaN,NaN,NaN,NaN,mumbai,indian,2027-05,sophia patel,NaN
18,.,2024-03-15,NaN,NaN,NaN,NaN,20%,NaN,NaN,NaN,shanghai,chinese,2026-08,NaN,NaN
19,.,2029-04,NaN,8°f,NaN,NaN,12%,NaN,NaN,NaN,chicago,NaN,2024-02-20,kevin white,NaN
20,.,2024-10-15,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,NaN,american,2026,david lee,NaN
21,.,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2028,NaN,NaN,72 to 75 years,maria,NaN
22,.,2027,john smith,NaN,NaN,NaN,20%,NaN,NaN,NaN,the united states,NaN,NaN,dr.,NaN
23,.,2024,NaN,21,NaN,NaN,25%,NaN,NaN,NaN,NaN,NaN,2029,emily chen,NaN
24,.,2025,NaN,NaN,NaN,NaN,15%,NaN,NaN,2024-10-10,australia,NaN,daily,michael brown,NaN
25,.,2024/11/12,NaN,NaN,NaN,the mayo clinic,12%,NaN,NaN,NaN,NaN,NaN,2026,sophia patel,NaN
26,.,2025,NaN,2500 to,NaN,NaN,NaN,NaN,NaN,2000,NaN,american,daily,kevin white,quarter 2 of 2028
27,.,2024-08-25,lisa nguyen,NaN,NaN,the european union,15%,NaN,NaN,NaN,NaN,NaN,2027,dr.,NaN
28,.,10/15/2024,NaN,NaN,NaN,the university of california,30%,NaN,NaN,NaN,NaN,NaN,2030,daniel kim,NaN
29,.,2029-08-20,olivia martin,2024/10/20,NaN,the canadian medical association,20%,NaN,NaN,NaN,canada,NaN,weekly,dr.,NaN
30,.,2024-10-15,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,NaN,NaN,2026,john smith,NaN
31,.,2024,NaN,NaN,NaN,the federal reserve,2% to 4%,NaN,NaN,NaN,NaN,NaN,2028,emily johnson,NaN
32,.,2027,NaN,NaN,$20 trillion,NaN,NaN,NaN,NaN,NaN,the united states,NaN,NaN,michael brown,NaN
33,.,2024-08-22,NaN,"5,000",NaN,jpmorgan chase,NaN,NaN,NaN,NaN,NaN,NaN,2029,robert williams,NaN
34,.,2025-08-20,NaN,NaN,NaN,the european union,80%,3%,NaN,NaN,NaN,NaN,2024-10-10,sarah lee,NaN
35,.,2024/11/12,NaN,NaN,NaN,the european central bank,5%,NaN,NaN,NaN,NaN,NaN,2027,david white,NaN
36,.,q3 of 2024,NaN,NaN,NaN,NaN,5% to 3%,NaN,NaN,NaN,NaN,NaN,2026,kevin davis,NaN
37,.,2024-09-18,NaN,NaN,NaN,NaN,10%,NaN,NaN,NaN,japan,NaN,2028,olivia martinez,NaN
38,.,2024-10-25,NaN,100 million,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2030,james wilson,NaN
39,.,2027,NaN,500,NaN,NaN,20%,NaN,NaN,NaN,the united states,NaN,2024-08-15,daniel kim,NaN

In [26]:
import spacy


nlp = spacy.load("en_core_web_sm")
doc = nlp(only_predictions[0])
word_embeddings = [token.vector for token in doc]
len(word_embeddings)

39

In [ ]:
word_embeddings.

In [ ]:
nlp = spacy.load("en_core_web_sm")
doc = nlp(text_data_sentence)
word_embeddings = [token.vector for token in doc]
word_embeddings

In [ ]:
only_predictions

In [ ]:
from spacy.vectors import Vectors
import numpy as np

# empty_vectors = Vectors(shape=(10000, 300))

data = np.zeros((len(only_predictions), 300), dtype='f')
vectors = Vectors(data=data, keys=only_predictions)
vectors

In [ ]:
# Convert vectors to a numpy array
vector_data = vectors.data
vector_data

In [ ]:

# Create a corresponding array of keys
vector_keys = np.array(only_predictions)
vector_keys

In [ ]:
prediction_labels = predictions_df['Prediction Label']
prediction_labels

In [ ]:
X_train, X_test, y_train, y_test = DataProcessing.split_data(vector_data, vector_keys)
X_train

## Play

- Remove once finalized

In [ ]:
pos_col_names = list(pos_df.columns)
for pos_col_name in pos_col_names:
    print(f"pos_col_name: {spacy.explain(pos_col_name)}")

In [ ]:
list(ner_df.columns)

In [ ]:
ner_col_names = list(ner_df.columns)
for ner_col_name in ner_col_names:
    print(ner_col_name)
    print(f"ner_col_name: {spacy.explain(ner_col_name)}")

- Patterns:
    - P1 goes to ?
        - $: SYM
        - 10: NUM
    - P2 goes to ?
        - 2024: NUM
        - -: SYM
        - 10: NUM
        - -: SYM
        - 20: NUM
- Write regex for \$\d+ and \d+-\d+-\d+? -> Manually label?

- Create new function in clean_predictions.py called `remove_symbols`

In [ ]:
texts = ["On [2024-10-20], [Samantha Thompson, a financial analyst] predicts that the [operating cash flow] at [Johnson & Johnson] [will likely] [increase] by [10 percent to $25 billion] in [2026 Q2]"]

texts_2 = "On [2024-10-20], [Samantha Thompson, a financial analyst] predicts that the [operating cash flow] at [Johnson & Johnson] [will likely] [increase] by [$10 percent to $25 billion] in [2026 Q2]"

texts_2 = "On [2024-10-20] $10 percent to $25 billion]"

texts_2_no_brackets = [texts_2.replace('[', '').replace(']', '')]
# ",".join(texts_2_no_brackets)
# print(texts_2_no_brackets)

# text_join = texts_2_no_brackets.split()
# print(text_join)

nlp = spacy.load("en_core_web_sm")
def extract_entities(data: pd.Series, nlp: spacy.Language):
    """
    Extract entities using the provided SpaCy NLP model.

    Parameters:
    -----------
    data : `pd.Series`
        A Series containing textual data for entity extraction.
    nlp : `spacy.Language`
        A SpaCy NLP model.

    Returns:
    --------
    tuple
        A tuple containing a list of entities and a set of unique NER tags.
    """
    entities = []
    all_ner_tags = set()
    label_counts = {}

    for doc in nlp.pipe(data, disable=["ner"]):
        # doc_entities = []
        # for ent in doc.ents:
        #     label = ent.label_
        #     text = ent.text
        #     print(label, text)
        print(doc)
        for token in doc:
            print(f"{token.text}: {token.pos_}")

        # entities.append(doc_entities)

    return entities, all_ner_tags

# extract_entities(texts, nlp)
# print()
print(texts_2_no_brackets)
extract_entities(texts_2_no_brackets, nlp)

2024: NUM
-: SYM
10: NUM
-: SYM
20: NUM


Create NER DATE from this

10: NUM
percent: NOUN

Johnson: PROPN
&: CCONJ
Johnson: PROPN

In [ ]:
pos_col_names = list(pos_df.columns)
for pos_col_name in pos_col_names:
    print(f"pos_col_name: {spacy.explain(pos_col_name)}")


list(ner_df.columns)

In [ ]:
ner_col_names = list(ner_df.columns)
for ner_col_name in ner_col_names:
    print(ner_col_name)
    print(f"ner_col_name: {spacy.explain(ner_col_name)}")

In [ ]:
# import numpy as np
# df_to_vectorize = shuffled_df
# col_name_to_vectorize = 'Base Predictions'

# def extract_text_to_vectorize(df_to_vectorize, col_name_to_vectorize):
#     text_to_vectorize = DataProcessing.df_to_list(df_to_vectorize, col_name_to_vectorize)
#     return text_to_vectorize

# def word_feature_extraction():
#     """Extract word vector embeddings using Spacy
    
#     Returns:
#     list
#         A list containing the word vector embeddings
#     """
#     text_to_vectorize = extract_text_to_vectorize(df_to_vectorize, col_name_to_vectorize)
#     word_embeddings = []
#     words = []
#     dfs = []
#     nlp = spacy.load("en_core_web_sm")

#     for sentence in text_to_vectorize:
#         print(sentence)
#         doc = nlp(sentence)
#         for token in doc:
#             # print(token.text, token.vector.size, token.vector)
#             avg_word_vector = np.mean(token.vector, axis=0)
#             print(token.text, avg_word_vector)
#             quit()
#     #         words.append(token.text)
#     #         word_embeddings.append(token.vector)

#     #     print(words, word_embeddings)
#     #     print()
#     #     df = pd.DataFrame(word_embeddings, columns=words)
#     # dfs.append(df)
#     # return dfs

In [ ]:
# word_feature_extraction()